apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic
  #clusterIP: None

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: vnatu/spring-pet-clinic:0.0.1
          name: petclinic
          ports:
            - containerPort: 8080
              name: petclinic
